{% set name = "fleur" %}
{% set version = "7.0" %}
{% set version_long = "MaX-R" + version %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://iffgit.fz-juelich.de/{{ name }}/{{ name }}/-/archive/{{ version_long }}/{{ name }}-{{ version_long }}.tar.gz
  sha256: c7fa8c9c53352393c3f4876dd0128b8691a455290b380078cb9e877005563e2e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - git
    - doxygen
    - python >=3
    - pytest
    - masci-tools
  host:
    - openmpi
    - scalapack
    - libblas  # [osx]
    - openblas * *openmp*  # [linux]
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - libxml2
    - fftw
    - hdf5 * *openmpi*
  run:
    - openmpi
    - scalapack
    - libblas  # [osx]
    - libblas * *openblas  # [linux]
    - openblas * *openmp*  # [linux]

test:
  commands:
    - inpgen -h
    - test -f $PREFIX/bin/fleur_MPI  # [unix]

about:
  home: https://www.flapw.de/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A feature-full, freely available FLAPW (full-potential linearized augmented planewave) code, based on density-functional theory
  description: |
    The FLAPW-Method is an all-electron method which within density functional theory is universally applicable to all atoms of the periodic table and to systems with compact as well as open structures. It is widely considered to be the most precise electronic structure method in solid state physics.
    an optional C extension for a serious speed boost.
  doc_url: https://www.flapw.de/
  dev_url: https://iffgit.fz-juelich.de/fleur/fleur

extra:
  recipe-maintainers:
    - ltalirz
    - janssenhenning
